name: capstone

dependencies:
    - ipykernel
    - jupyter
    - matplotlib
    - pandas
    - pip>=19.0
    - python=3.9
    - pyyaml
    - scikit-learn
    - seaborn
    - pip:
        - scipy==1.8
        - exif
        - opencv-python
        - fastapi
        - uvicorn